FORMAT: 1A

# Bogass

API de l'application Bogass, application ne faisant rien


## Authentication
Actuellement l'API n'intègre pas de système d'authentification

# Group Files

Récuperer les fichiers

## File [/files/{uuid}]

+ Parameters
    + uuid (number) - ID of the Question in the form of an integer

### Delete [DELETE]

+ Response 204

## Raw file [/files/{uuid}/raw]

### Fichier [GET]

+ Response 200 (application/json; charset=utf-8)