FORMAT: 1A

# Bogass

API de l'application Bogass, l'application des bogass 

# GET /

+ Response 200 (application/json; charset=utf-8)
    
    + Body

            { 
                "message": "Hello World!"
            }

# GET /bogass/{id}

+ Parameters
    + id: 1 (number) - Identifiant du bogass

+ Response 200 (application/json; charset=utf-8)

    + Body

            {
                "id": 1,
                "name": "Jean Smaug"
            } 
