name: 🧊 Tesseract
# cmake build of tesseract and training tools on ubuntu and macOS homebrew using Ninja.
# test command line version of tesseract. run basicapitest.
on:
  #push:
  workflow_dispatch:
  pull_request:

jobs:
  build-tesseract:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout Tesseract 5.1.0
        uses: actions/checkout@v2
        with:
          repository: tesseract-ocr/tesseract
          ref: 5.1.0
          path: tesseract

      - name: Install dependencies
        run: |
          sudo apt-get install libleptonica-dev -y

      - name: Build Tesseract
        run: |
          cd tesseract
          ./autogen.sh
          mkdir -p bin/release
          cd bin/release
          ../../configure --disable-openmp --disable-shared 'CXXFLAGS=-g -O2 -fno-math-errno -Wall -Wextra -Wpedantic'
          make
          echo "Print version"
          ./tesseract -v
          strip ./tesseract

      - uses: actions/upload-artifact@v3
        with:
          name: tesseract
          path: tesseract/bin/release/tesseract
